# Generated by Django 2.1.12 on 2019-11-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='academic_displines',
            new_name='academic_disciplines',
        ),
    ]
