# Generated by Django 2.1.12 on 2019-11-05 04:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_disciplines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='campus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
