# Generated by Django 2.1.12 on 2019-10-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='first_academic_discipline',
            new_name='first_academic_disciplines',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='second_academic_discipline',
            new_name='second_academic_disciplines',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='third_academic_discipline',
            new_name='third_academic_disciplines',
        ),
    ]
