# Generated by Django 2.1.12 on 2019-10-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lab',
            old_name='topics',
            new_name='topic',
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('B1', "Bachelor's 1"), ('B2', "Bachelor's 2"), ('B3', "Bachelor's 3"), ('B4', "Bachelor's 4"), ('M1', "Master's 1"), ('M2', "Master's 2"), ('D', 'PhD'), ('na', 'Other')], default='na', max_length=2),
        ),
    ]
