# Generated by Django 2.1.12 on 2019-11-05 04:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0002_auto_20191105_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='academic_disciplines',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=3),
        ),
    ]
