# Generated by Django 2.1.12 on 2019-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0003_auto_20191105_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
