# Generated by Django 2.1.12 on 2019-11-14 12:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_rater_app', '0004_auto_20191105_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.RemoveField(
            model_name='course',
            name='syllabus_urls',
        ),
        migrations.AddField(
            model_name='course',
            name='schools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, null=True, size=3),
        ),
        migrations.AddField(
            model_name='course',
            name='syllabus_url',
            field=models.URLField(blank=True),
        )
    ]
